# Generated by Django 5.2.6 on 2025-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapping',
            fields=[
                ('shortcode', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('original_url', models.CharField()),
            ],
        ),
    ]
