# Generated by Django 5.2.6 on 2025-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmapping',
            name='shortcode',
        ),
        migrations.AddField(
            model_name='urlmapping',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlmapping',
            name='short_url',
            field=models.CharField(default='a', unique=True),
            preserve_default=False,
        ),
    ]
