# Generated by Django 5.2.6 on 2025-09-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_website', '0002_remove_urlmapping_shortcode_urlmapping_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
