# Generated by Django 5.2.6 on 2025-09-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_website', '0003_alter_urlmapping_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmapping',
            old_name='short_url',
            new_name='shortcode',
        ),
    ]
