# Generated by Django 5.2.6 on 2025-10-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_website', '0004_rename_short_url_urlmapping_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='original_url',
            field=models.CharField(unique=True),
        ),
    ]
