# Generated by Django 5.2.6 on 2025-11-14 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_website', '0005_alter_urlmapping_original_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(unique=True)),
                ('hashed_password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='UserUrlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortener_website.urlmapping')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortener_website.useraccount')),
            ],
        ),
    ]
