# Generated by Django 5.2.6 on 2025-11-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_website', '0006_useraccount_userurlmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmapping',
            name='clicks',
            field=models.BigIntegerField(default=0),
        ),
    ]
